--12 NETFLIX BUSINESS PROBLEMS
--1.COUNT THE NUMBER OF MOVIES VS TV SHOWS
SELECT TYPE,
COUNT(*) AS TOTAL_CONTENT
FROM
	NETFLIX
GROUP BY
	TYPE;

--2.FIND THE MOST COMMON RATING FOR MOVIES AND TV SHOWS
SELECT 
    TYPE,
    RATING
FROM
(SELECT
	TYPE,
	RATING,
	COUNT(*),
	RANK()OVER(PARTITION BY TYPE ORDER BY COUNT(*)DESC) AS RANKING
FROM
	NETFLIX
GROUP BY
	1,2)AS T1
	WHERE RANKING=1;

--3.LIST ALL MOVIES AND ITS TITLE RELEASED IN SPECIFIC YEAR 2020
SELECT
	TYPE,
	TITLE,
	RELEASE_YEAR
FROM
	NETFLIX
WHERE
	TYPE = 'Movie'
	AND RELEASE_YEAR = 2020;

--4.FIND THE TOP 5 COUNTRIES WITH THE MOST CONTENT ON NETFILX
SELECT
    UNNEST (STRING_TO_ARRAY(country,',')) as new_country,
	COUNT(show_id) AS taotal_content
FROM NETFLIX
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;

--5.IDENTIFY THE LONGEST MOVIE SHOW ONLY TYPE,TITLE,DURATION?
SELECT TYPE,TITLE,DURATION FROM NETFLIX
WHERE 
    TYPE='Movie'
	AND 
	duration=(SELECT MAX(duration)FROM NETFLIX);

--6.FIND CONTENT ADDED IN THE LAST 5 YEARS AND ONLY SHOW THE TYPE,DATE_ADDED
SELECT
	TYPE,
	DIRECTOR,
	DATE_ADDED
FROM
	NETFLIX 
WHERE
	TO_DATE(DATE_ADDED, 'Month DD,YYYY') >= CURRENT_DATE - INTERVAL '5 years'
ORDER BY 2 ASC
LIMIT 5;

--7.FIND ALL THE MOVIES/TV SHOWS BY DIRECTOR 'RAJIV CHILAKA'
SELECT
	TYPE,
	TITLE,
	DIRECTOR
FROM
	NETFLIX
WHERE
	DIRECTOR ILIKE '%Rajiv Chilaka%';

--8.COUNT OF NUMBER CONTENT ITEMS IN EACH GENRE
SELECT
     UNNEST(STRING_TO_ARRAY(listed_in, ','))AS genre,
	 COUNT(show_id)
FROM netflix
GROUP BY 1
LIMIT 5;

--9.FIND EACH YEAR AND THE AVGRAGE NUMBERS OF CONTENT RELEASE IN INDIA N NETFLIX,RETURN TOP 5 YEAR WITH HIGHEST AVG CONTENT RELEASE:
SELECT 
    EXTRACT (YEAR FROM TO_DATE(date_added,'Month DD,YYYY')) AS YEAR,
	COUNT(*) AS yearly_content,
	ROUND(
	COUNT(*)::NUMERIC/(SELECT COUNT(*)FROM NETFLIX WHERE COUNTRY='India')::NUMERIC*100,2) AS Avg_Content_Per_Year
FROM NETFLIX
WHERE COUNTRY='India'
GROUP BY 1
ORDER BY 1 ASC
LIMIT 5;

--10.LIST ALL MOVIES THAT ARE DOCUMENTARIES AND SHOW TYPE,LISTED_IN
SELECT
    TYPE,
	LISTED_IN
SELECT
FROM
	NETFLIX
WHERE
	LISTED_IN ILIKE '%documentaries%'
LIMIT 5;

--11.FIND CONTENT SHOW_ID,TYPE,TITLE WITHOUT A DIRECTOR 
SELECT
	SHOW_ID,
	TYPE,
	TITLE,
	DIRECTOR
FROM
	NETFLIX
WHERE
	DIRECTOR IS NULL 
	LIMIT 5;

--12.FIND HOW MANY MOVIES ACTOR 'SALMAN KHAN'APPEARED IN LAST 10 YEARS SHOW TYPE,TITLE,RELEASE_YEAR
SELECT
	TYPE,
	TITLE,
	RELEASE_YEAR
FROM
	NETFLIX
WHERE
	CASTS ILIKE '%Salman Khan%'
	AND RELEASE_YEAR > EXTRACT(YEAR FROM CURRENT_DATE) -10



	
 
